# Generated by Django 2.2.3 on 2019-11-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudobjects', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudobject',
            name='crudcover',
            field=models.ImageField(blank=True, upload_to='crudcovers/'),
        ),
    ]
