# Generated by Django 2.2.3 on 2019-11-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudobjects', '0003_crudobject_crudcover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crudobject',
            options={'permissions': [('special_status', 'Can read all crudobjects')]},
        ),
    ]
